### ISSUE TITLE
Potential for partial/complete dataloss

### ISSUE THREAD

**Issue by bpatters** [jcasbin/jdbc-adapter#14]
Failure in the savePolicy function can lead to a complete loss of all data because savePolicy doesn't use transactions AND:

1. First drops the table
2. Recreates the table.
3. Executes a batch of inserts to save the policy.

If 1 succeed and a failure occurs anytime after it can lead to a partial or complete data loss.

It'd be much safer if it:
1. Started a transaction
2. Deleted everything in the table (not drop table, mysql doesn't support DML transactions)
3. Inserted the new policy.
4. Committed the transaction.

I actually don't see any usage of transactions in this Adapter, which is worrisome, but maybe I'm missing something?

**Comment by hsluoyz** [comment]
@fangzhengjin @nodece @gopherJ

**Comment by nodece** [comment]
@hsluoyz  I will take up it.

**Comment by nodece** [comment]
Hi @bpatters , I submitted a PR, Could you review the #15 ?

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/jcasbin/jdbc-adapter/pull/15

**Comment by hsluoyz** [comment]
v1.1.4 has been released on Maven and GitHub: https://github.com/jcasbin/jdbc-adapter

**Comment by hsluoyz** [comment]
@nodece v2.0.0 has been released. You can edit the release text: https://github.com/jcasbin/jdbc-adapter/releases/tag/v2.0.0
