### ISSUE TITLE
Takes 2 hrs to load 4L Policy records

### ISSUE THREAD

**Issue by arafat-java** [jcasbin/jdbc-adapter#22]
I have been trying the JDBC adapter for jcasbin. While trying to insert approx 4L records for policy it took more than 2 hours
The code that I used was as follows

```java
public static void main(String[] a) throws Exception {

JDBCAdapter a1 = new JDBCAdapter(driver, url, username, password);
Enforcer e = new Enforcer("C:\\temp\\jcasbin_try\\model.conf", a1);

long start = System.currentTimeMillis();
System.out.println("Starting at " + new Date());
for (int object = 101; object <= 20000; object++) {
	for (int identity = 1; identity <= 20; identity++) {
		e.addPolicy("rdt00"+identity, "PlannerObject_"+object, "read");
	}
}
long end = System.currentTimeMillis();
System.out.println("Ending addPolicy at " + new Date() + " total Time : " + (end - start));

e.savePolicy();
System.out.println("Ending savePolicy at " + new Date() + " total Time : " + (System.currentTimeMillis() - end));
}
```

Am I doing something wrong ?

**Comment by hsluoyz** [comment]
@shy1st can you help look at this issue?

**Comment by shy1st** [comment]
@arafat-java Would you mind providing the model.conf?

**Comment by arafat-java** [comment]
Here is the model.conf

[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act

**Comment by shy1st** [comment]
@arafat-java It seems that we create too many database connection。We will fix the problem. Thanks for you for discovering this problem

**Comment by hsluoyz** [comment]
@arafat-java what do you mean by "4L"? million or what?

**Comment by shy1st** [comment]
@arafat-java At present, it takes an average of one minute to import 10000 pieces of data into the database. Do you think that is ok?

**Comment by arafat-java** [comment]
I guess "one minute to import 10000 pieces of data into the database" should be ok
By "4L" I mean 4,00,000

**Comment by arafat-java** [comment]
When do you think the fix for " too many database connection" be available

**Comment by hsluoyz** [comment]
@arafat-java ok.

@shy1st plz make a PR which fixed this issue. Thanks!

**Comment by shy1st** [comment]
@arafat-java I  have submitted the pr. Please wait patiently for the audit.
