### ISSUE TITLE
2.0.2 not loading old data with jcasbin >1.10.2

### ISSUE THREAD

**Issue by lanmarti** [jcasbin/jdbc-adapter#36]
Can we get a new release which includes https://github.com/jcasbin/jdbc-adapter/pull/33 ?

Context:
Before jcasbin 1.10.2, the following code would load all policies currently stored in the DB:

```java
this.jdbcAdapter = new JDBCAdapter(this.dataSourceFactory.createDataSource(props));
final Model model = CoreEnforcer.newModel(this.getResourceFileAsString("rbac_model.conf"));
this.enforcer = new Enforcer(model, this.jdbcAdapter);
```
With jcasbin 1.10.2 and up, existing policies are no longer loaded. This seems to be because of the isFiltered check introduced in  https://github.com/casbin/jcasbin/commit/c61a1abaf50c5ebdfd2d1d6316390349a105125a . https://github.com/jcasbin/jdbc-adapter/pull/33 sets the default value for isFiltered to false, which I assume will fix the issue.

**Comment by hsluoyz** [comment]
Plz use version > v2.1.0: https://github.com/jcasbin/jdbc-adapter/releases
