### ISSUE TITLE
Switch travis-ci to GitHub Actions CI and setup semantic-release

### ISSUE THREAD

**Issue by hsluoyz** [jcasbin/jdbc-adapter#37]
Use this as a reference: https://github.com/jcasbin/jdbc-adapter/pull/34

**Comment by hsluoyz** [comment]
@tangyang9464

**Comment by hsluoyz** [comment]
@seriouszyx can you help work on this?

**Comment by seriouszyx** [comment]
OK

**Comment by hsluoyz** [comment]
@seriouszyx we need to finish this first, so we can have an auto release when https://github.com/jcasbin/jdbc-adapter/pull/39 is merged.

**Comment by seriouszyx** [comment]
@hsluoyz I've written the GitHub Actions scripts on my own repo and built passing. Plz grant me permission to check the secrets.

**Comment by hsluoyz** [comment]
@seriouszyx done
