### ISSUE TITLE
`casbin_sequence` is generated even when `casbin_rule` table is made beforehand using `GenerationType.IDENTITY`

### ISSUE THREAD

**Issue by offset-null1** [jcasbin/jdbc-adapter#59]
I implicitly created `casbin_rule` table with Id generation type as `IDENTITY`. But it created `casbin_sequence` which wasn't required and happened  because of 
` case "PostgreSQL":
                sql = renderActualSql("CREATE SEQUENCE IF NOT EXISTS CASBIN_SEQUENCE START 1;");`

in `JDBCBaseAdapter.java` .
It should only be executed when the table doesn't exist otherwise the generation of sequence is redundant.

**Comment by hsluoyz** [comment]
@OutOfEastGate

**Comment by OutOfEastGate** [comment]
@offset-null1 Thank you for your feedback. I will deal with it soon.

**Comment by hsluoyz** [comment]
@offset-null1 are you a user or contributor?

**Comment by offset-null1** [comment]
@hsluoyz I'm using this module to contribute to this [issue](https://github.com/casbin/jcasbin/issues/104#issue-728918532).

**Comment by imp2002** [comment]
> I implicitly created `casbin_rule` table with Id generation type as `IDENTITY`

Adapter adapter = new JDBCAdapter(dataSource, removePolicyFailed, tableName, autoCreateTable)
Have created table yourself, pass autoCreateTable with `false`? Does this solve your problem

`JDBCAdapter(DataSource dataSource, boolean removePolicyFailed, String tableName, boolean autoCreateTable)`

**Comment by offset-null1** [comment]
Yes, that prevents the creation of `casbin_sequence` but as the default is
true, I feel before generating the sequence there should be a check if the
table exists or not. In my case I didn't set it to false but had a table
already created, still the sequence was generated i.e., I ended up having 2
sequences in the database.

**Comment by OutOfEastGate** [comment]
> Yes, that prevents the creation of `casbin_sequence` but as the default is true, I feel before generating the sequence there should be a check if the table exists or not. In my case I didn't set it to false but had a table already created, still the sequence was generated i.e., I ended up having 2 sequences in the database.

I know what you mean.By default, we create casbin_sequence. If you have your own requirements, you can modify the parameters of casbin_sequence directly.In mybatis adapter, sequence is not created by default. Of course, we will refine this section to check the existence of the table before creating the casbin_sequence.

**Comment by offset-null1** [comment]
Okay, thank you for the clarification
