### ISSUE TITLE
jdbc-adapter hot reload polices

### ISSUE THREAD

**Issue by wangyuefan09** [jcasbin/jdbc-adapter#67]

**Comment by hsluoyz** [comment]
@wangyuefan09 what do you mean by "hot reload"? Casbin doesn't have a concept called "hot reload"

**Comment by wangyuefan09** [comment]
All right. What I mean is that when a new policy is added, the method "e.loadPolicy()" needs to be manually called to take effect.

**Comment by wangyuefan09** [comment]
All right. What I mean is that when a new policy is added, the method "e.loadPolicy()" needs to be manually called to take effect.

**Comment by hsluoyz** [comment]
@wangyuefan09 

1. If you call `addPolicy()` API in the same enforcer, that enforcer will already have that policy automatically.
2. If you call `addPolicy()` API in another enforcer that shares the same adapter (aka DB), you need to use Watcher (https://casbin.org/docs/watchers/) to sync the updated policy between enforcers

**Comment by wangyuefan09** [comment]
OK, thanks
