### ISSUE TITLE
Question: Table structure for storing policy in database.

### ISSUE THREAD

**Issue by vaibhavkhl** [jcasbin/jdbc-adapter#7]
Hi,
I need to store my policy in database. I will be using postgresql. 
So do I need to have a specific table structure or It can be custom?

For example I want to store this policy
```
p, nsm_role, /national_sales, *
p, rsm_role, /regional_sales, *
p, asm_role, /area_sales, *


g, nsm_role, rsm_role
g, rsm_role, asm_role

g, nsm_user, nsm_role
g, nsm_user, admin_role
g, rsm_user, rsm_role
g, asm_user, asm_role
```

From seeing the codebase it seems there should be columns like p_type, v1, v2, v3 etc.
But what does this mean, can you explain please?

Can I have multiple tables like ```user_roles_table``` for g mapping and ```policy_table``` for p mapping?

Thanks

**Comment by hsluoyz** [comment]
```
p_type = p
v1 = nsm_role
v2 = /national_sales
v3 = *
```

If you need to use multiple tables, you need to implement a custom adapter.

**Comment by vaibhavkhl** [comment]
ok thanks and similarly for storing g mapping 
```p_type = g```
right?

**Comment by hsluoyz** [comment]
Yes.
