### ISSUE TITLE
can not work with oracle

### ISSUE THREAD

**Issue by Fengxq2014** [jcasbin/jdbc-adapter#8]
oracle not support `CREATE TABLE IF NOT EXISTS`,`DROP TABLE IF EXISTS`,`rewriteBatchedStatements`

**Comment by hsluoyz** [comment]
Hi @Fengxq2014 , I don't have a Oracle database for me to test. Can you help make a PR about it?

**Comment by Fengxq2014** [comment]
please check #9

**Comment by hsluoyz** [comment]
Merged.
